/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#343536',
        'on-tertiary-container': '#006f48',
        'on-tertiary': '#003822',
        'on-secondary-fixed-variant': '#43474c',
        'secondary-fixed-dim': '#c3c7cd',
        'surface-tint': '#74d4e8',
        'inverse-primary': '#006877',
        'primary-fixed': '#a3eeff',
        'surface-container-highest': '#343536',
        'on-tertiary-fixed-variant': '#005234',
        'surface-bright': '#38393a',
        'inverse-on-surface': '#303032',
        'on-error': '#690005',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#52de9e',
        'background': '#121315',
        'on-secondary': '#2c3136',
        'surface-container': '#1f2021',
        'primary-fixed-dim': '#74d4e8',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#b4b9bf',
        'tertiary': '#eaffef',
        'on-background': '#e3e2e3',
        'secondary-fixed': '#dfe3e9',
        'outline-variant': '#3e494b',
        'on-primary-fixed-variant': '#004e5a',
        'tertiary-fixed': '#72fbb9',
        'on-primary-fixed': '#001f25',
        'secondary': '#c3c7cd',
        'surface-container-high': '#292a2b',
        'on-surface': '#e3e2e3',
        'outline': '#879395',
        'primary': '#effcff',
        'primary-container': '#8cebff',
        'secondary-container': '#454a4f',
        'on-surface-variant': '#bdc8cb',
        'surface-container-low': '#1b1c1d',
        'tertiary-container': '#6cf6b4',
        'error': '#ffb4ab',
        'surface': '#121315',
        'surface-container-lowest': '#0d0e0f',
        'surface-dim': '#121315',
        'inverse-surface': '#e3e2e3',
        'on-primary': '#00363e',
        'on-secondary-fixed': '#171c20',
        'on-primary-container': '#006b7a',
        'on-tertiary-fixed': '#002112'
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['Geist', 'monospace'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-verdict': ['Geist', 'sans-serif'],
        'display-verdict-mobile': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'title-lg': ['Inter', 'sans-serif'],
        'label-instrument': ['Geist', 'monospace'],
        'label-tabular': ['Geist', 'monospace'],
        'monumental-numeral': ['Geist', 'sans-serif']
      }
    }
  },
  plugins: [],
};
