import { AnalysisResult, CybercrimeDraftReport } from '../../../shared/types/index.js';
import { OFFICIAL_REPORTING_RESOURCES } from '../../../shared/constants/index.js';
import { generateReportIntegrityHash } from '../utils/hasher.js';

export class ReportGenerator {
  static generateTextSummary(analysis: AnalysisResult): string {
    const integrityHash = generateReportIntegrityHash(analysis);

    return `=====================================================
BOBSEC FORENSIC INCIDENT BRIEFING
AI-Powered Anti-Scam Triage Engine (Indian Jurisdiction)
=====================================================

INCIDENT IDENTIFIER: ${analysis.id}
ANALYSIS DATE/TIME : ${new Date(analysis.createdAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST
INTEGRITY HASH     : ${integrityHash}
VERDICT            : ${analysis.verdict.level.toUpperCase()} (${analysis.verdict.score}/100)
CONFIDENCE         : ${analysis.verdict.confidence}%
CATEGORY           : ${analysis.verdict.categoryLabel}

--- EXECUTIVE SUMMARY ---
${analysis.verdict.summary}

--- KEY RED FLAGS IDENTIFIED ---
${analysis.redFlags.map((rf, idx) => `[${idx + 1}] ${rf.title} (${rf.severity})\n    ${rf.description}\n    Evidence: "${rf.evidenceSnippet || 'N/A'}"`).join('\n\n')}

--- EXTRACTED SUSPICIOUS ENTITIES ---
${analysis.entities.map((e) => `• ${e.type.padEnd(12)}: ${e.maskedValue} [${e.status}] - ${e.notes || 'Identified'}`).join('\n')}

--- IMMEDIATE DIRECTIVES & RECOMMENDED ACTIONS ---
${analysis.recommendations.map((r, idx) => `${idx + 1}. [${r.type}] ${r.text}\n   Context: ${r.context || 'Standard defensive procedure'}`).join('\n')}

--- OFFICIAL REPORTING ASSISTANCE ---
If financial fraud has occurred, immediately contact:
• National Cybercrime Helpline: ${OFFICIAL_REPORTING_RESOURCES.nationalHelpline} (Toll-Free, 24x7)
• National Cybercrime Reporting Portal: ${OFFICIAL_REPORTING_RESOURCES.nationalCybercrimePortal}
• DoT Chakshu Portal: ${OFFICIAL_REPORTING_RESOURCES.chakshuPortal}

--- STATUTORY DISCLAIMER ---
This forensic assessment is generated by BobSec automated multi-agent heuristic models for civilian guidance. It does not constitute formal legal testimony or law enforcement certification. BobSec is not an agency of the Police, CBI, or Government of India.
=====================================================`;
  }

  static generateCybercrimeDraft(analysis: AnalysisResult): CybercrimeDraftReport {
    const phoneEntities = analysis.entities.filter((e) => e.type === 'PHONE').map((e) => e.value);
    const urlEntities = analysis.entities.filter((e) => e.type === 'URL').map((e) => e.value);
    const upiEntities = analysis.entities.filter((e) => e.type === 'UPI').map((e) => e.value);
    const amountEntities = analysis.entities.filter((e) => e.type === 'AMOUNT').map((e) => e.value);

    return {
      incidentId: analysis.id,
      timestamp: analysis.createdAt,
      scamCategory: analysis.verdict.categoryLabel,
      severity: analysis.verdict.level,
      incidentSummary: `Received suspicious extortion/fraud message exhibiting high-risk patterns of ${analysis.verdict.categoryLabel}. Suspect demanded immediate compliance, unauthorized credentials, or money transfer under threat or deception.`,
      suspiciousSender: phoneEntities[0] || 'Unknown Originator',
      phoneNumbers: phoneEntities,
      urls: urlEntities,
      upiIds: upiEntities,
      amounts: amountEntities,
      evidenceText: analysis.input.sanitizedText,
      recommendedOfficialAction:
        'Requesting immediate flagging of suspect phone numbers on DoT Chakshu portal and placing a defensive lien on suspect UPI/Bank accounts under Golden Hour cybercrime protocols.',
      officialHelpline: OFFICIAL_REPORTING_RESOURCES.nationalHelpline,
      portalUrl: OFFICIAL_REPORTING_RESOURCES.nationalCybercrimePortal
    };
  }
}

